import { GoogleGenAI, Modality } from "@google/genai";
import { AspectRatio } from "../types";

export type ModelType = 'imagen-4.0-generate-001' | 'gemini-2.5-flash-image';

// Экспортируем AspectRatio для компонентов
export type { AspectRatio };

const dataUrlToInlineData = (dataUrl: string) => {
    const [header, base64Data] = dataUrl.split(',');
    if (!header || !base64Data) {
        throw new Error("Invalid data URL format");
    }
    const mimeTypeMatch = header.match(/:(.*?);/);
    if (!mimeTypeMatch || !mimeTypeMatch[1]) {
        throw new Error("Could not extract MIME type from data URL");
    }
    const mimeType = mimeTypeMatch[1];
    return {
        inlineData: {
            data: base64Data,
            mimeType,
        },
    };
};

export const generateImage = async (
    apiKey: string,
    prompt: string, 
    aspectRatio: AspectRatio, 
    model: ModelType, 
    referenceImages: string[] // base64 data URLs
): Promise<string[]> => {
  try {
    if (!apiKey) {
      throw new Error("API ключ не предоставлен");
    }
    const ai = new GoogleGenAI({ apiKey });
    
    if (model === 'imagen-4.0-generate-001') {
        const response = await ai.models.generateImages({
            model: 'imagen-4.0-generate-001',
            prompt: prompt,
            config: {
                numberOfImages: 1,
                outputMimeType: 'image/png',
                aspectRatio: aspectRatio,
            },
        });

        if (response.generatedImages && response.generatedImages.length > 0) {
            return response.generatedImages
                .filter(img => img?.image?.imageBytes)
                .map(img => `data:image/png;base64,${img.image!.imageBytes}`);
        } else {
            throw new Error("No images were generated by Imagen 4.");
        }
    } else if (model === 'gemini-2.5-flash-image') {
        const parts: any[] = [];
        
        if (referenceImages.length > 0) {
            parts.push(...referenceImages.map(dataUrlToInlineData));
        }
        
        if (prompt.trim()) {
             parts.push({ text: prompt });
        }

        if (parts.length === 0) {
            throw new Error("A prompt or at least one reference image is required for Gemini Flash.");
        }
        
        // Используем оригинальную модель из gemini-image-chat
        // Если не работает, пробуем альтернативные модели
        const modelsToTry = [
            'gemini-2.5-flash-image',
            'gemini-1.5-flash',
            'gemini-1.5-pro'
        ];
        
        let lastError: Error | null = null;
        
        for (const modelName of modelsToTry) {
            try {
                console.log(`🔄 Пробую модель: ${modelName}`);
                const response = await ai.models.generateContent({
                    model: modelName,
                    contents: { parts },
                    config: {
                        responseModalities: [Modality.IMAGE],
                    },
                });

                const generated: string[] = [];
                if (response.candidates && response.candidates.length > 0) {
                    const candidate = response.candidates[0];
                    if (candidate?.content?.parts) {
                        for (const part of candidate.content.parts) {
                            if (part.inlineData && part.inlineData.data && part.inlineData.mimeType) {
                                const base64ImageBytes: string = part.inlineData.data;
                                const mimeType: string = part.inlineData.mimeType;
                                generated.push(`data:${mimeType};base64,${base64ImageBytes}`);
                            }
                        }
                    }
                }

                if (generated.length > 0) {
                    console.log(`✅ Успешно сгенерировано изображение с моделью: ${modelName}`);
                    return generated;
                } else {
                    throw new Error(`Модель ${modelName} не вернула изображение.`);
                }
            } catch (err: any) {
                lastError = err;
                console.warn(`⚠️ Модель ${modelName} не сработала:`, err.message);
                
                // Если это ошибка квоты или доступа, не пробуем другие модели
                if (err.message?.includes('quota') || 
                    err.message?.includes('429') ||
                    err.message?.includes('billed') ||
                    err.message?.includes('INVALID_ARGUMENT')) {
                    break;
                }
            }
        }
        
        // Если все модели не сработали, выбрасываем последнюю ошибку
        if (lastError) {
            throw lastError;
        }
        
        throw new Error("No images were generated by Gemini Flash.");
    } else {
        throw new Error(`Unsupported model: ${model}`);
    }
  } catch (error: any) {
    console.error("Error generating image:", error);
    
    // Обработка специфичных ошибок
    if (error?.message) {
      const errorMsg = error.message.toLowerCase();
      
      // Ошибка квоты
      if (errorMsg.includes('quota') || errorMsg.includes('429') || error?.error?.code === 429) {
        const retryAfter = error?.error?.details?.find((d: any) => d['@type']?.includes('RetryInfo'))?.retryDelay || '';
        throw new Error(`Превышена квота API. ${retryAfter ? `Попробуйте снова через ${retryAfter}` : 'Пожалуйста, подождите немного и попробуйте снова.'}`);
      }
      
      // Imagen требует биллинга
      if (errorMsg.includes('billed') || errorMsg.includes('only accessible to billed')) {
        throw new Error('Imagen 4 доступен только для платных пользователей Google Cloud. Пожалуйста, используйте модель "Gemini Flash Image".');
      }
      
      // Другие ошибки
      if (error instanceof Error) {
        throw new Error(`Ошибка генерации изображения: ${error.message}`);
      }
    }
    
    throw new Error("Не удалось сгенерировать изображение. Попробуйте снова позже.");
  }
};

