import { GoogleGenAI, Modality } from "@google/genai";
import { AspectRatio } from "../types";

export type ModelType = 'imagen-4.0-generate-001' | 'gemini-2.5-flash-image';

const dataUrlToInlineData = (dataUrl: string) => {
    const [header, base64Data] = dataUrl.split(',');
    if (!header || !base64Data) {
        throw new Error("Invalid data URL format");
    }
    const mimeTypeMatch = header.match(/:(.*?);/);
    if (!mimeTypeMatch || !mimeTypeMatch[1]) {
        throw new Error("Could not extract MIME type from data URL");
    }
    const mimeType = mimeTypeMatch[1];
    return {
        inlineData: {
            data: base64Data,
            mimeType,
        },
    };
};

export const generateImage = async (
    apiKey: string,
    prompt: string, 
    aspectRatio: AspectRatio, 
    model: ModelType, 
    referenceImages: string[] // base64 data URLs
): Promise<string[]> => {
  try {
    const ai = new GoogleGenAI({ apiKey });
    
    if (model === 'imagen-4.0-generate-001') {
        const response = await ai.models.generateImages({
            model: 'imagen-4.0-generate-001',
            prompt: prompt,
            config: {
                numberOfImages: 1,
                outputMimeType: 'image/png',
                aspectRatio: aspectRatio,
            },
        });

        if (response.generatedImages && response.generatedImages.length > 0) {
            return response.generatedImages.map(img => `data:image/png;base64,${img.image.imageBytes}`);
        } else {
            throw new Error("No images were generated by Imagen 4.");
        }
    } else if (model === 'gemini-2.5-flash-image') {
        const parts: any[] = [];
        
        if (referenceImages.length > 0) {
            parts.push(...referenceImages.map(dataUrlToInlineData));
        }
        
        if (prompt.trim()) {
             parts.push({ text: prompt });
        }

        if (parts.length === 0) {
            throw new Error("A prompt or at least one reference image is required for Gemini Flash.");
        }
        
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash-image',
            contents: { parts },
            config: {
                responseModalities: [Modality.IMAGE],
            },
        });

        const generated: string[] = [];
        if (response.candidates && response.candidates.length > 0) {
            for (const part of response.candidates[0].content.parts) {
                if (part.inlineData) {
                    const base64ImageBytes: string = part.inlineData.data;
                    generated.push(`data:${part.inlineData.mimeType};base64,${base64ImageBytes}`);
                }
            }
        }

        if (generated.length > 0) {
            return generated;
        } else {
             throw new Error("No images were generated by Gemini Flash.");
        }
    } else {
        throw new Error(`Unsupported model: ${model}`);
    }
  } catch (error) {
    console.error("Error generating image:", error);
     if (error instanceof Error) {
        throw new Error(`Failed to generate image. Details: ${error.message}`);
    }
    throw new Error("Failed to generate image. An unknown error occurred.");
  }
};

